CREATE TABLE Jugadores (
  IDJUGADOR INT PRIMARY KEY,
  NOMBRE VARCHAR(50)
);

CREATE TABLE Equipos (
  IDEQUIPO INT PRIMARY KEY,
  NOMBRE VARCHAR(50)
);

CREATE TABLE Temporadas (
  IDTEMPORADA INT PRIMARY KEY,
  ANIO INT
);

CREATE TABLE Campeonatos (
  CODIGOCAMPEONATO INT PRIMARY KEY,
  NOMBRE VARCHAR(50),
  ANIO INT
);


CREATE TABLE GolesPorTemporada (
  IDJUGADOR INT,
  IDTEMPORADA INT,
  IDEQUIPO INT,
  GOLES INT,
  FOREIGN KEY (IDJUGADOR) REFERENCES Jugadores(IDJUGADOR),
  FOREIGN KEY (IDTEMPORADA) REFERENCES Temporadas(IDTEMPORADA),
  FOREIGN KEY (IDEQUIPO) REFERENCES Equipos(IDEQUIPO)
);

CREATE TABLE GolesPorCampeonato (
  IDJUGADOR INT,
  CODIGOCAMPEONATO INT,
  IDEQUIPO INT,
  GOLES INT,
  FOREIGN KEY (IDJUGADOR) REFERENCES Jugadores(IDJUGADOR),
  FOREIGN KEY (CODIGOCAMPEONATO) REFERENCES Campeonatos(CODIGOCAMPEONATO),
  FOREIGN KEY (IDEQUIPO) REFERENCES Equipos(IDEQUIPO)
);
