CREATE TABLE Empresas (
  IDEMPRESA INT PRIMARY KEY,
  NOMBRE VARCHAR(50)
);


CREATE TABLE Productos (
  IDPRODUCTO INT PRIMARY KEY,
  IDEMPRESA INT,
  IDPROMOTOR INT,
  NOMBRE VARCHAR(50),
  FOREIGN KEY (IDEMPRESA) REFERENCES Empresas(IDEMPRESA),
  FOREIGN KEY (IDPROMOTOR) REFERENCES Promotores(IDPROMOTOR)
);


CREATE TABLE Promotores (
  IDPROMOTOR INT PRIMARY KEY,
  IDEMPRESA INT,
  NOMBRE VARCHAR(50),
  FOREIGN KEY (IDEMPRESA) REFERENCES Empresas(IDEMPRESA)
);


ALTER TABLE Productos
ADD CONSTRAINT FK_Productos_Promotores
FOREIGN KEY (IDPROMOTOR) REFERENCES Promotores(IDPROMOTOR)NOT NULL;
